version: '3.9'

services:
  telegram-bot:
    build: .
    container_name: control-bot
    env_file:
      - .env
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: control-bot-tunnel
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - telegram-bot
